mqtt:
  enabled: false
go2rtc:
  streams:
    sala:
      - rtsp://usuario:senha@192.168.68.202:554/stream1
    varanda:
      - rtsp://usuario:senha@192.168.68.201:554/stream1
    quarto:
      - rtsp://usuario:senha@192.168.68.203:554/stream1
cameras:
  sala: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/sala?video&audio
          roles:
            - detect
    detect:
      enabled: true # <---- disable detection until you have a working camera feed
      width: 1280
      height: 720
      fps: 1
varanda: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/varanda?video&audio
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 1
  quarto: # <------ Name the camera
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/quarto?video&audio
          roles:
            - detect
    detect:
      enabled: true
      width: 1280
      height: 720
      fps: 1
version: 0.15-1
record:
  enabled: true
  retain:
    days: 3
    mode: all
  alerts:
    retain:
      days: 30
      mode: motion
  detections:
    retain:
      days: 15
      mode: motion
